#!/bin/sh

case "$1" in
  start)
    ifconfig eth0 hw ether 42:4C:45:00:00:00
    ifconfig eth0 mtu 1500
    ifconfig lo 127.0.0.1
    #eth0 dhcp-close
    ifconfig eth0 192.168.1.168 netmask 255.255.255.0
    route add default gw 192.168.1.254 eth0
    ifconfig eth0 up
    ip -6 route add default via fe80::1 dev eth0

    # telnetd &
    #  uftpd -o "ftp=21 tftp=69 writable" /
    ;;
  stop)
    ifconfig eth0 down
    ;;
  *)
    $0 start
    ;;
esac

exit 0