# ipc_share.cmake
include(${CMAKE_CURRENT_LIST_DIR}/common/common.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/control/control.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/data_format/data_format.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/design/design.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/encrypt/md5/md5.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ffmpeg/ffmpeg.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/hardware/hardware.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/network/network.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/network/tcp/tcp.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/network/udp/udp.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/network/websocket/websocket.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/protocols/protocols.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/push_stream/push_stream.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ret/ret.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/standard/standard.cmake)
